export var album = {
  categories:[
    {nom:'Cuisines X', numero:'1', photos:[
      {id:'1', nom:'Photo 1', desc:'Consectetur adipiscing elit. Sed nunc, neque, tellus, lacus condimentum pulvinar turpis eu auctor. Commodo dui eget ultrices ac consectetur amet, pulvinar purus. Curabitur ut pellentesque fermentum netus tincidunt molestie scelerisque. Est tellus consequat consectetur nisl, commodo. '},
      {id:'2', nom:'Photo 2', desc:'Handy Dandy, controversy surrounds him. He been around the world and back again. Something in the moonlight still hounds him. Handy Dandy, just like sugar and candy. Handy Dandy, if every bone in his body was broken he would never admit it. He got an all-girl orchestra and when he says. “Strike up the band,” they hit it. Handy Dandy, Handy Dandy. You say, “What are ya made of?” He says, “Can you repeat what you said?” You’ll say, “What.'},
      {id:'3', nom:'Photo 3', desc:'It was late last night when the boss came home. To a deserted mansion and a desolate throne. Servant said, “Boss, the lady’s gone. She left this morning just ‘fore dawn.” “You got something to tell me, tell it to me, man. Come to the point as straight as you can.” “Old Henry Lee, chief of the clan, Came riding through the woods and took her by the hand.” The boss he laid back flat on his bed. He cursed the heat.'},
      {id:'1', nom:'Photo 4', desc:'Yes, the sign on the cross. Is just a sign on the cross. Well, there is some on every chisel. And there is some in the championship, too. Oh, when your, when your days are numbered. And your nights are long. You might think you’re weak. But I mean to say you’re strong. Yes you are, if that sign on the cross. If it begins to worry you. Well, that’s all right because sing a song. And all your troubles will pass right on through.'}
    ]},
    {nom:'Cuisines Y', numero:'2', photos:[
      {id:'2', nom:'Photo 5', desc:'I’m out here a thousand miles from my home. Walkin’ a road other men have gone down. I’m seein’ your world of people and things. Your paupers and peasants and princes and kings. Hey, hey, Woody Guthrie, I wrote you a song. ’Bout a funny ol’ world that’s a-comin’ along. Seems sick an’ it’s hungry, it’s tired an’ it’s torn. It looks like it’s a-dyin’ an’ it’s hardly been born. Hey, Woody Guthrie, but I know that you know. All the things that I’m a-sayin’.'},
      {id:'3', nom:'Photo 6', desc:'Go ahead and talk about him because he makes you doubt. Because he has denied himself the things that you can’t live without. Laugh at him behind his back just like the others do. Remind him of what he used to be when he comes walkin’ through. He’s the property of Jesus. Resent him to the bone. You got something better. You’ve got a heart of stone. Stop your conversation when he passes on the street. Hope he falls upon himself, oh, won’t that be sweet. Because.'},
      {id:'1', nom:'Photo 7', desc:'’Twas in another lifetime, one of toil and blood. When blackness was a virtue and the road was full of mud. I came in from the wilderness, a creature void of form. “Come in,” she said, “I’ll give you shelter from the storm” And if I pass this way again, you can rest assured. I’ll always do my best for her, on that I give my word. In a world of.Description 7'}
    ]},
    {nom:'Cuisines Z', numero:'3', photos:[
      {id:'2', nom:'Photo 8', desc:'Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw that minstrel boy a coin? Who’s gonna let it down easy to save his soul? Oh, Lucky’s been drivin’ a long, long time. And now he’s stuck on top of the hill. With twelve forward gears, it’s been a long hard climb. And with all of them ladies, though, he’s lonely still. Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw. 8'},
      {id:'3', nom:'Photo 9', desc:'I’m goin’ down south. ’Neath the borderline. I’m goin’ down south. ’Neath the borderline. Some fat momma. Kissed my mouth one time. Well, I needed it this morning. Without a shadow of doubt. My suitcase is packed. My clothes are hangin’ out. San Francisco’s fine. You sure get lots of sun. San Francisco is fine. You sure get lots of sun. But I’m used to four seasons. California’s got but one. Well, I got.'},
      {id:'1', nom:'Photo 10', desc:'I wandered again to my home in the mountain. Where in youth’s early days I was happy and free. I looked for my friends but I never could find them. I found they were all rank strangers to me. Ev’rybody I met seemed to be a rank stranger. No mother or dad not a friend could I see. They knew not my name and I knew not their faces. I found they were all rank strangers to me. They all moved a way, said a. 10'},
      {id:'2', nom:'Photo 11', desc:'Don’t ever try to change me, I been in this thing too long. There’s nothin’ you can say or do. To make me think I’m wrong. Well, I’m goin’ off to Libya, There’s a guy I gotta see. He`s been living there three years now, In an oil refinery. I`ve got my mind made up. Oh, I ’ve got my mind made up. Call your Ma in Tallahassee. Tell her her baby’s on the line. Tell her not to worry. Everything is gonna be fine. Well, I gave you all.'}
    ]},
    {nom:'Cuisines 1', numero:'3', photos:[
      {id:'2', nom:'Photo 8', desc:'Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw that minstrel boy a coin? Who’s gonna let it down easy to save his soul? Oh, Lucky’s been drivin’ a long, long time. And now he’s stuck on top of the hill. With twelve forward gears, it’s been a long hard climb. And with all of them ladies, though, he’s lonely still. Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw. 8'},
    ]},
    {nom:'Cuisines 2', numero:'3', photos:[
      {id:'2', nom:'Photo 8', desc:'Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw that minstrel boy a coin? Who’s gonna let it down easy to save his soul? Oh, Lucky’s been drivin’ a long, long time. And now he’s stuck on top of the hill. With twelve forward gears, it’s been a long hard climb. And with all of them ladies, though, he’s lonely still. Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw. 8'},
      {id:'3', nom:'Photo 9', desc:'I’m goin’ down south. ’Neath the borderline. I’m goin’ down south. ’Neath the borderline. Some fat momma. Kissed my mouth one time. Well, I needed it this morning. Without a shadow of doubt. My suitcase is packed. My clothes are hangin’ out. San Francisco’s fine. You sure get lots of sun. San Francisco is fine. You sure get lots of sun. But I’m used to four seasons. California’s got but one. Well, I got.'},
    ]},
    {nom:'Cuisines 5', numero:'3', photos:[
      {id:'2', nom:'Photo 8', desc:'Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw that minstrel boy a coin? Who’s gonna let it down easy to save his soul? Oh, Lucky’s been drivin’ a long, long time. And now he’s stuck on top of the hill. With twelve forward gears, it’s been a long hard climb. And with all of them ladies, though, he’s lonely still. Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw. 8'},
      {id:'3', nom:'Photo 9', desc:'I’m goin’ down south. ’Neath the borderline. I’m goin’ down south. ’Neath the borderline. Some fat momma. Kissed my mouth one time. Well, I needed it this morning. Without a shadow of doubt. My suitcase is packed. My clothes are hangin’ out. San Francisco’s fine. You sure get lots of sun. San Francisco is fine. You sure get lots of sun. But I’m used to four seasons. California’s got but one. Well, I got.'},
      {id:'1', nom:'Photo 10', desc:'I wandered again to my home in the mountain. Where in youth’s early days I was happy and free. I looked for my friends but I never could find them. I found they were all rank strangers to me. Ev’rybody I met seemed to be a rank stranger. No mother or dad not a friend could I see. They knew not my name and I knew not their faces. I found they were all rank strangers to me. They all moved a way, said a. 10'},
      {id:'2', nom:'Photo 11', desc:'Don’t ever try to change me, I been in this thing too long. There’s nothin’ you can say or do. To make me think I’m wrong. Well, I’m goin’ off to Libya, There’s a guy I gotta see. He`s been living there three years now, In an oil refinery. I`ve got my mind made up. Oh, I ’ve got my mind made up. Call your Ma in Tallahassee. Tell her her baby’s on the line. Tell her not to worry. Everything is gonna be fine. Well, I gave you all.'},
      {id:'2', nom:'Photo 11', desc:'Don’t ever try to change me, I been in this thing too long. There’s nothin’ you can say or do. To make me think I’m wrong. Well, I’m goin’ off to Libya, There’s a guy I gotta see. He`s been living there three years now, In an oil refinery. I`ve got my mind made up. Oh, I ’ve got my mind made up. Call your Ma in Tallahassee. Tell her her baby’s on the line. Tell her not to worry. Everything is gonna be fine. Well, I gave you all.'}
    ]},
    {nom:'Cuisines 6', numero:'3', photos:[
      {id:'2', nom:'Photo 8', desc:'Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw that minstrel boy a coin? Who’s gonna let it down easy to save his soul? Oh, Lucky’s been drivin’ a long, long time. And now he’s stuck on top of the hill. With twelve forward gears, it’s been a long hard climb. And with all of them ladies, though, he’s lonely still. Who’s gonna throw that minstrel boy a coin? Who’s gonna let it roll? Who’s gonna throw. 8'},
      {id:'3', nom:'Photo 9', desc:'I’m goin’ down south. ’Neath the borderline. I’m goin’ down south. ’Neath the borderline. Some fat momma. Kissed my mouth one time. Well, I needed it this morning. Without a shadow of doubt. My suitcase is packed. My clothes are hangin’ out. San Francisco’s fine. You sure get lots of sun. San Francisco is fine. You sure get lots of sun. But I’m used to four seasons. California’s got but one. Well, I got.'},
      {id:'1', nom:'Photo 10', desc:'I wandered again to my home in the mountain. Where in youth’s early days I was happy and free. I looked for my friends but I never could find them. I found they were all rank strangers to me. Ev’rybody I met seemed to be a rank stranger. No mother or dad not a friend could I see. They knew not my name and I knew not their faces. I found they were all rank strangers to me. They all moved a way, said a. 10'},
      {id:'2', nom:'Photo 11', desc:'Don’t ever try to change me, I been in this thing too long. There’s nothin’ you can say or do. To make me think I’m wrong. Well, I’m goin’ off to Libya, There’s a guy I gotta see. He`s been living there three years now, In an oil refinery. I`ve got my mind made up. Oh, I ’ve got my mind made up. Call your Ma in Tallahassee. Tell her her baby’s on the line. Tell her not to worry. Everything is gonna be fine. Well, I gave you all.'},
      {id:'2', nom:'Photo 11', desc:'Don’t ever try to change me, I been in this thing too long. There’s nothin’ you can say or do. To make me think I’m wrong. Well, I’m goin’ off to Libya, There’s a guy I gotta see. He`s been living there three years now, In an oil refinery. I`ve got my mind made up. Oh, I ’ve got my mind made up. Call your Ma in Tallahassee. Tell her her baby’s on the line. Tell her not to worry. Everything is gonna be fine. Well, I gave you all.'},
      {id:'2', nom:'Photo 11', desc:'Don’t ever try to change me, I been in this thing too long. There’s nothin’ you can say or do. To make me think I’m wrong. Well, I’m goin’ off to Libya, There’s a guy I gotta see. He`s been living there three years now, In an oil refinery. I`ve got my mind made up. Oh, I ’ve got my mind made up. Call your Ma in Tallahassee. Tell her her baby’s on the line. Tell her not to worry. Everything is gonna be fine. Well, I gave you all.'}
    ]}
  ]
}